push = require 'lib/push'
Class = require'lib/class'

require 'src/constants'
require 'src/StateMachine'
require 'src/Board'
require 'src/Box'
require 'src/Board'
require 'src/Util'
require 'src/Player'
require 'src/Move'

require 'src/states/BaseState'
require 'src/states/PlayState'
require 'src/states/GameOverState'

require 'src/pieces/Piece'
require 'src/pieces/Bishop'
require 'src/pieces/King'
require 'src/pieces/Knight'
require 'src/pieces/Pawn'
require 'src/pieces/Queen'
require 'src/pieces/Rook'
